config/routes.rb
Forem::Application.routes.draw do
  root :to => "forums#index"

  resources :forums

  resources :topics do
    resources :messages
  end

  resources :users
  match 'signup' => 'users#new'

  resources :sessions
  match 'login' => 'sessions#new'
  match 'logout' => 'sessions#destroy'

end

app/models/forum.rb
class Forum < ActiveRecord::Base
  attr_accessible :desc, :name

  has_many :topics
  has_many :messages, :through => :topics

  validates_presence_of :name, :desc
  validates_uniqueness_of :name

  def recent_message
    messages.last
  end
end

app/models/message.rb
class Message < ActiveRecord::Base
  attr_accessible :content, :title, :user_id, :topic_id

  belongs_to :forum
  belongs_to :topic
  belongs_to :user
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  attr_accessible :content, :title, :user_id, :forum_id

  belongs_to :forum
  belongs_to :user
  has_many :messages

  validates_presence_of :title, :content, :forum_id, :user_id
end

app/models/user.rb
require 'bcrypt'
class User < ActiveRecord::Base
  attr_accessible :email, :password, :role
  attr_accessor :password

  before_save :encrypt_password

  validates_presence_of :email
  validates_presence_of :password, :on => :create
  validates_presence_of :role
  validates_uniqueness_of :email
  validates_confirmation_of :password

  has_many :topics
  has_many :messages

  def role?(rooli)
    role == rooli.to_s
  end

  def self.authenticate(email, pwd)
    user = User.find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(pwd, user.password_salt)
      user
    else
      false
    end
  end

  private
  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  helper_method :current_user, :logged_in?, :admin?

  rescue_from ActionController::RoutingError do
    render :file => "public/404.html"
  end

  private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    current_user != nil
  end

  def admin?
    current_user.role?(:admin) if logged_in?
  end
end

app/controllers/forums_controller.rb
class ForumsController < ApplicationController
  before_filter :authorize!, :only => [:new]

  def index
    @forums = Forum.all
  end

  def show
    @forum = Forum.find(params[:id])
  end

  def new
    @forum = Forum.new
  end

  def create
    @forum = Forum.new(params[:forum])
    if @forum.save
      redirect_to @forum
    else
      render :new
    end
  end

  private
  def authorize!
    if !logged_in?
      redirect_to login_url
    elsif !admin?
      raise ActionController::RoutingError.new('Not Found')
    end
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def create
    @topic = Topic.find(params[:topic_id])
    message = @topic.messages.build(params[:message])
    if message.save
      redirect_to @topic
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.authenticate(params[:email], params[:password])
    if user
      session[:user_id] = user.id
      redirect_to root_url
    else
      flash.now.alert = "Email and/or password mismatch"
      render :new
    end
  end

  def destroy
    @current_user = session[:user_id] = nil
    redirect_to root_url
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  def show
    @topic = Topic.find(params[:id])
  end

  def new
    @forum = Forum.find(params[:forum_id])
    @topic = @forum.topics.build
  end

  def create
    @topic = Topic.new(params[:topic])
    if @topic.save
      redirect_to @topic
    else
      render :new
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      redirect_to root_url
    else
      render :new
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/forums_helper.rb
module ForumsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/forums/index.html.erb
<div id="forums">
  <% for forum in @forums %>
    <div class="forum">
      <h2>
        <%= link_to(forum.name, forum) %>
        <%= forum.desc %>
      </h2>

      <div class="topics-count">
        <%= pluralize(forum.topics.count, "topic") %>
      </div>

      <div class="messages-count">
        <%= pluralize(forum.messages.count, "message") %>
      </div>

      <div class="recent-message">
        <%= forum.recent_message.user.email if forum.recent_message %>
      </div>
    </div>
  <% end %>
</div>

<% if admin? %>
  <div class="actions">
    <p><%= link_to("New forum", new_forum_path) %></p>
  </div>
<% end %>

app/views/forums/new.html.erb
<div class="formy left">
  <h2>New forum</h2>

  <%= form_for(@forum) do |f| %>
    <div class="field">
      <%= f.text_field :name, :placeholder => "Name" %>
    </div>

    <div class="field">
      <%= f.label :desc, "Description" %><br>
      <%= f.text_area :desc, :size => "80x8" %>
    </div>

    <div class="button">
      <%= f.submit "Create" %>
    </div>
  <% end %>
</div>

app/views/forums/show.html.erb
<div class="crumbs">
  <%= link_to(@forum.name, @forum) %>
</div>

<h2>Topics</h2>

<div class="actions">
  <p>
  <%= link_to("New topic", new_topic_path(:forum_id => @forum.id)) %>
  </p>
</div>

<% for topic in @forum.topics %>
  <div class="topic">
    <h3><%= link_to(topic.title, topic) %></h3>
    <div class="starter">
      by <span><%= topic.user.email %></span>
    </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kustelu</title>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>

    <header>
    <h1><%= link_to("Kustelu", root_path) %></h1>
    </header>

    <div class="user-nav">
      <% if current_user %>
        <p>
        <%= current_user.email %> (<%= current_user.role %>) |
        <%= link_to("logout", logout_path) %>
        </p>
      <% else %>
        <%= link_to("login", login_path) %>
      <% end %>
    </div>

    <% flash.each do |type, msg| %>
      <%= content_tag(:div, msg, :class => "flash #{type}") %>
    <% end %>

    <%= yield %>

  </body>
</html>

app/views/topics/new.html.erb
<div class="crumbs">
  <%= link_to(@topic.forum.name, @topic.forum) %> &raquo;
  New topic
</div>

<div class="formy left">
  <h2>New topic</h2>

  <%= form_for(@topic) do |f| %>
    <div class="field">
      <%= f.text_field :user_id, :placeholder => "User ID" %>
    </div>

    <div class="field">
      <%= f.text_field :title, :placeholder => "Title" %>
    </div>
    
    <div class="field">
      <%= f.text_area :content %>
    </div>

    <div class="button">
      <%= f.submit "Create" %>
    </div>
  <% end %>
</div>

app/views/topics/show.html.erb
<div class="crumbs">
  <%= link_to(@topic.forum.name, @topic.forum) %> &raquo;
  <%= @topic.title %>
</div>

<div id="messages">
  <h2><%= @topic.title %></h2>
  <div class="message">
    <div class="content">
      <%= @topic.content %>
    </div>
    <div class="meta">
      <span class="poster"><%= @topic.user.email %></span>
      <span class="date"><%= time_ago_in_words(@topic.created_at) %> ago</span>
    </div>
  </div>

  <% for message in @topic.messages %>
    <div class="message">
      <div class="content">
        <%= message.content %>
      </div>
      <div class="meta">
        <span class="poster"><%= message.user.email %></span>
        <span class="date"><%= time_ago_in_words(message.created_at) %> ago</span>
      </div>
    </div>
  <% end %>
</div>

<div class="formy">
  <%= form_for([@topic, Message.new]) do |f| %>
    <h3>Reply to this topic</h3>
    <%= f.text_field :user_id %>
    <div class="field">
      <%= f.label :content %><br>
      <%= f.text_area :content, :size => "80x8" %>
    </div>

    <div class="button">
      <%= f.submit "Reply" %>
    </div>
  <% end %>
</div>

app/views/users/new.html.erb
<div class="formy left">
  <h2>Sign up</h2>

  <%= form_for(@user) do |f| %>
    <% if @user.errors.any? %>
      <div class="errors">
        <h3>Errors</h3>

        <ul>
          <% for message in @user.errors.full_messages %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.text_field :email, :placeholder => "Email" %>
    </div>

    <div class="field">
      <%= f.password_field :password, :placeholder => "Password" %>
    </div>

    <div class="button left">
      <%= f.submit "Send" %>
    </div>
  <% end %>
</div>